FROM debian:jessie
RUN apt-get update && apt-get install -y \
  dnsutils \
  htop \
  lsof \
  ncdu \
  pv \
  screen \
  strace \
  ltrace \
  tmux \
  vim \
  mtr \
  curl \
  wget \
  netcat \
  --
